#!/usr/bin/env python3
"""Show projects currently available."""

# base imports
import json

# establish parameters
project_list = json.load(open("setup/project_list.json", "r"))
hidden_list = json.load(open("setup/hidden_project_list.json", "r"))

print(f"\n\tActive projects: {project_list}")
print(f"\n\tHidden projects: {hidden_list}\n")
